"""agregar campo activo al modelo material

Revision ID: 51b7b98f23dd
Revises: a6b0a95a75d3
Create Date: 2025-07-29 23:46:23.138673

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51b7b98f23dd'
down_revision = 'a6b0a95a75d3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.add_column(sa.Column('activo', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('material', schema=None) as batch_op:
        batch_op.drop_column('activo')

    # ### end Alembic commands ###
