""" agregar usuario_id a modelo notificaiones

Revision ID: 565cf4d266e9
Revises: 339eb5c8367e
Create Date: 2025-07-26 00:54:27.329119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '565cf4d266e9'
down_revision = '339eb5c8367e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usuario_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'user', ['usuario_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('notificacion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('usuario_id')

    # ### end Alembic commands ###
