"""reconstruir migraciones

Revision ID: a6b0a95a75d3
Revises: 
Create Date: 2025-07-29 19:56:45.438651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6b0a95a75d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('descripcion', sa.String(length=200), nullable=True),
    sa.Column('stock', sa.Float(), nullable=True),
    sa.Column('stock_minimo', sa.Integer(), nullable=True),
    sa.Column('unidad', sa.String(length=50), nullable=True),
    sa.Column('en_devolucion', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=200), nullable=False),
    sa.Column('rol', sa.String(length=20), nullable=False),
    sa.Column('foto', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('movimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('solicitado_por_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('observacion_almacenista', sa.Text(), nullable=True),
    sa.Column('evidencia', sa.String(length=200), nullable=True),
    sa.Column('evidencia_almacenista', sa.String(length=200), nullable=True),
    sa.Column('visible_en_existencias', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['material_id'], ['material.id'], name='fk_movimiento_material'),
    sa.ForeignKeyConstraint(['solicitado_por_id'], ['user.id'], name='fk_movimiento_solicitante'),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], name='fk_movimiento_usuario'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mensaje', sa.String(length=300), nullable=False),
    sa.Column('nivel', sa.String(length=10), nullable=False),
    sa.Column('leida', sa.Boolean(), nullable=True),
    sa.Column('fecha', sa.DateTime(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['user.id'], name='fk_notificacion_usuario'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notificacion')
    op.drop_table('movimiento')
    op.drop_table('user')
    op.drop_table('material')
    # ### end Alembic commands ###
